#!/usr/bin/env bash

[ "$DEBUG" == 'true' ] && set -x

# Fix issue with dpkg-reconfigure and locales not installed "perl: warning: Setting locale failed."
unset LANG

cd /etc/postfix

# Copy default spool from cache
if [ ! "$(ls -A /var/spool/postfix)" ]; then
   cp -a /var/spool/postfix.cache/* /var/spool/postfix/
fi

# Defaults
if [ -z "$MAILNAME" ]; then
    echo "postfix >> Error: MAILNAME not specified"
    exit 128
fi

if [ -z "$MYNETWORKS" ]; then
    MYNETWORKS='127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16'
    echo "postfix >> Warning: MYNETWORKS not specified, allowing all private IPs"
fi

if [ -z "$SIZELIMIT" ]; then
    SIZELIMIT=15728640  # 10Meg with headroom
fi

# DKIM
if [ "${USE_DKIM}" == "yes" ]; then
    # TODO s6-svwait for dkim
    echo "postfix >> Enabling dkim milter"
    postconf -e milter_protocol="6"
    postconf -e milter_default_action="accept"
    postconf -e smtpd_milters="inet:localhost:8891"
    postconf -e non_smtpd_milters="inet:localhost:8891"
fi

# TLS
: ${USE_TLS:='yes'}
: ${TLS_KEY:='/etc/ssl/private/ssl-cert-snakeoil.key'}
: ${TLS_CRT:='/etc/ssl/certs/ssl-cert-snakeoil.pem'}
: ${TLS_CA:=''}

# General
: ${POSTFIX_ADD_MISSING_HEADERS:='no'}

echo "postfix >> Setting smtpd_use_tls to $USE_TLS"
postconf -e smtpd_use_tls="$USE_TLS"

if [ "${USE_TLS}" == "yes" ]; then
    if [ "${TLS_KEY}" == "/etc/ssl/private/ssl-cert-snakeoil.key" ]; then
        echo "postfix >> Generating snakeoil SSL cert"
        dpkg-reconfigure -f noninteractive ssl-cert
    fi
    echo "postfix >> Setting smtpd_tls parameters"
    postconf -e smtp_tls_security_level="may"
    postconf -e smtp_tls_loglevel="1"
    postconf -e smtpd_tls_key_file="$TLS_KEY"
    postconf -e smtpd_tls_cert_file="$TLS_CRT"
    postconf -e smtpd_tls_CAfile="$TLS_CA"
fi

# Configure Postfix General parameters
echo "postfix >> Setting mailname to $MAILNAME"
echo $MAILNAME > /etc/mailname
postconf -e myhostname="$MAILNAME"
postconf -e mydestination="$MAILNAME"

echo "postfix >> Setting mynetworks to $MYNETWORKS"
postconf -e mynetworks="$MYNETWORKS"

echo "postfix >> Setting message_size_limit to $SIZELIMIT"
postconf -e message_size_limit="$SIZELIMIT"

echo "postfix >> Setting always_add_missing_headers to $POSTFIX_ADD_MISSING_HEADERS"
postconf -e always_add_missing_headers="$POSTFIX_ADD_MISSING_HEADERS"

# exit cleanly
trap "{ /usr/sbin/service postfix stop; }" EXIT

# Cleanup stale pids incase we don't exit cleanly
rm -f /var/spool/postfix/pid/*

# start postfix
/usr/sbin/service postfix start

sleep 10 # wait for startup

# watch for postfix exit
while kill -0 $(pidof master) 2>/dev/null; do
	sleep 1
done
