#!/usr/bin/env bash

[ "$DEBUG" == 'true' ] && set -x

cd /etc/postfix

# Copy default spool from cache
if [ ! "$(ls -A /var/spool/postfix)" ]; then
   cp -a /var/spool/postfix.cache/* /var/spool/postfix/
fi

# Defaults
if [ -z "$MAILNAME" ]; then
    echo "Error: MAILNAME not specified"
    exit 128
fi

if [ -z "$MYNETWORKS" ]; then
    MYNETWORKS='127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16'
    echo "Warning: MYNETWORKS not specified, allowing all private IPs"
fi

if [ -z "$SIZELIMIT" ]; then
    SIZELIMIT=15728640  # 10Meg with headroom
fi

# TLS
: ${USETLS:='yes'}
: ${TLSKEY:='/etc/ssl/private/ssl-cert-snakeoil.key'}
: ${TLSCRT:='/etc/ssl/certs/ssl-cert-snakeoil.pem'}
: ${TLSCA:=''}

echo "Setting smtpd_use_tls to $USETLS"
postconf -e smtpd_use_tls="$USETLS"

if [ "${USETLS}" == "yes" ]; then
    if [ "${TLSKEY}" == "/etc/ssl/private/ssl-cert-snakeoil.key" ]; then
        echo "Generating snakeoil SSL cert"
        dpkg-reconfigure -f noninteractive ssl-cert
    fi
    echo "Setting smtpd_tls parameters"
    postconf -e smtpd_tls_key_file="$TLSKEY"
    postconf -e smtpd_tls_cert_file="$TLSCRT"
    postconf -e smtpd_tls_CAfile="$TLSCA"
fi

# Configure Postfix General parameters
echo "Setting mailname to $MAILNAME"
echo $MAILNAME > /etc/mailname
postconf -e myhostname="$MAILNAME"
postconf -e mydestination="$MAILNAME"

echo "Setting mynetworks to $MYNETWORKS"
postconf -e mynetworks="$MYNETWORKS"

echo "Setting message_size_limit to $SIZELIMIT"
postconf -e message_size_limit="$SIZELIMIT"

# exit cleanly
trap "{ /usr/sbin/service postfix stop; }" EXIT

# Cleanup stale pids incase we don't exit cleanly
rm -f /var/spool/postfix/pid/*

# start postfix
/usr/sbin/service postfix start

sleep 10 # wait for startup

# watch for postfix exit
while kill -0 $(pidof master) 2>/dev/null; do
	sleep 1
done
