#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# Defaults
: "${SIZELIMIT:=15728640}"  # 10Meg with headroom
: "${RELAYHOST:=}" # empty

# TLS
: "${USE_TLS:=yes}"
: "${TLS_SECURITY_LEVEL:=may}"
: "${TLS_KEY:=/etc/ssl/private/ssl-cert-snakeoil.key}"
: "${TLS_CRT:=/etc/ssl/certs/ssl-cert-snakeoil.pem}"
: "${TLS_CA:=}"

# General
: "${POSTFIX_ADD_MISSING_HEADERS:=no}"
: "${INET_PROTOCOLS:=all}"

# Fix issue with dpkg-reconfigure and locales not installed "perl: warning: Setting locale failed."
unset LANG

cd /etc/postfix

# Copy default spool from cache
if [ ! "$(ls -A /var/spool/postfix)" ]; then
   cp -a /var/spool/postfix.cache/* /var/spool/postfix/
else
  # Fix spool directory permissions
  chgrp -R postdrop /var/spool/postfix/public
  chgrp -R postdrop /var/spool/postfix/maildrop
  postfix set-permissions
fi

# DKIM
if [ "${USE_DKIM}" == "yes" ]; then
    # TODO s6-svwait for dkim
    echo "postfix >> Enabling dkim milter"
    postconf -e milter_protocol="6"
    postconf -e milter_default_action="accept"
    postconf -e smtpd_milters="inet:localhost:8891"
    postconf -e non_smtpd_milters="inet:localhost:8891"
fi

echo "postfix >> Setting smtpd_use_tls to ${USE_TLS}"
postconf -e smtpd_use_tls="${USE_TLS}"

if [ "${USE_TLS}" == "yes" ]; then
    if [ "${TLS_KEY}" == "/etc/ssl/private/ssl-cert-snakeoil.key" ]; then
        echo "postfix >> Generating snakeoil SSL cert"
        dpkg-reconfigure -f noninteractive ssl-cert
    fi
    echo "postfix >> Setting smtp_tls parameters"
    postconf -e smtp_tls_security_level="${TLS_SECURITY_LEVEL}"
    postconf -e smtp_tls_CApath="/etc/ssl/certs"
    postconf -e smtp_tls_loglevel="1"
    echo "postfix >> Setting smtpd_tls parameters"
    postconf -e smtpd_tls_key_file="${TLS_KEY}"
    postconf -e smtpd_tls_cert_file="${TLS_CRT}"
    postconf -e smtpd_tls_CAfile="${TLS_CA}"
fi

# Configure Postfix General parameters
echo "postfix >> Setting mailname to ${MAILNAME}"
postconf -e myorigin="${MAILNAME}"
postconf -e myhostname="${MAILNAME}"
postconf -e mydestination="${MAILNAME}"

echo "postfix >> Setting mynetworks to ${MYNETWORKS}"
postconf -e mynetworks="${MYNETWORKS}"

echo "postfix >> Setting message_size_limit to ${SIZELIMIT}"
postconf -e message_size_limit="${SIZELIMIT}"

if [ -n "${RELAYHOST}" ]; then
  echo "postfix >> Setting relayhost to ${RELAYHOST}"
  postconf -e relayhost="${RELAYHOST}"
fi

if [ "${RELAYHOST_AUTH}" == "yes" ]; then
    echo "postfix >> Enabling relayhost authentication"
    touch /etc/postfix/sasl-passwords
    postconf -e smtp_sasl_auth_enable=yes
    postconf -e smtp_sasl_security_options=noanonymous
    postconf -e smtp_sasl_password_maps=hash:/etc/postfix/sasl-passwords
    # require encryption with relayhost auth
    postconf -e smtp_use_tls=yes
    postconf -e smtp_tls_security_level=encrypt
    postconf -e smtp_sasl_mechanism_filter="PLAIN LOGIN"
fi

if [ -n "${RELAYHOST_PASSWORDMAP}" ]; then
    echo "postfix >> Generating relayhost password map"
    truncate --size 0 /etc/postfix/sasl-passwords
    IFS=',' read -r -a PASSWORDMAP <<< "${RELAYHOST_PASSWORDMAP}"
    for P in "${PASSWORDMAP[@]}"; do
        IFS='|' read -ra MAP <<< "$P"
        HOST=${MAP[0]}
        USER=${MAP[1]}
        PASS=${MAP[2]}
        echo "postfix >> Adding user ${HOST} with user: ${USER}."
        echo "${HOST} ${USER}:${PASS}" >> /etc/postfix/sasl-passwords
    done
    postmap hash:/etc/postfix/sasl-passwords
fi

echo "postfix >> Setting always_add_missing_headers to ${POSTFIX_ADD_MISSING_HEADERS}"
postconf -e always_add_missing_headers="${POSTFIX_ADD_MISSING_HEADERS}"

echo "postfix >> Setting inet_protocols to ${INET_PROTOCOLS}"
postconf -e inet_protocols="${INET_PROTOCOLS}"

if [[ "${HEADER_CHECKS}" == "true" ]]; then
  echo "postfix >> Setting header_checks"
  postconf -e smtp_header_checks="regexp:/etc/postfix/header_checks"
fi

if [ -n "${BOUNCE_ADDRESS}" ]; then
  echo "postfix >> Setting bounce address to ${BOUNCE_ADDRESS}"
  postconf -e notify_classes="bounce"
  postconf -e bounce_notice_recipient="${BOUNCE_ADDRESS}"
fi

# Client Authentication (SASL)
if [ ! -z "${SMTPD_USERS}" ]; then
  echo "postfix >> Setting smtpd sasl auth"
  postconf -e smtpd_sasl_auth_enable="yes"
  postconf -e broken_sasl_auth_clients="yes"
  postconf -e smtpd_sasl_local_domain='$myhostname'
  printf "%s\n" \
    "pwcheck_method: auxprop" \
    "auxprop_plugin: sasldb" \
    "mech_list: PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM" \
  > /etc/postfix/sasl/smtpd.conf
  while IFS=':' read -r user password; do
    echo "postfix >> Adding user SASL user: ${user}"
    echo "${password}" | saslpasswd2 -p -c -u "${MAILNAME}" "${user}"
  done < <(echo "${SMTPD_USERS}" | tr ',' '\n')
  chown postfix:sasl /etc/sasldb2
  # /etc/sasldb2 needs to be in the postfix chroot, this is a bit of a hack
  sed -i -E 's/etc\/host\.conf etc\/nsswitch\.conf etc\/nss_mdns\.config"/etc\/host.conf etc\/nsswitch.conf etc\/nss_mdns.config etc\/sasldb2"/' /usr/lib/postfix/configure-instance.sh
fi

# Cleanup stale pids incase we hadn't exited cleanly
rm -f /var/spool/postfix/pid/*

# configure instance (populate etc)
/usr/lib/postfix/configure-instance.sh

# check postfix is happy (also will fix some things)
echo "postfix >> Checking Postfix Configuration"
postfix check

# start postfix in foreground
exec /usr/sbin/postfix start-fg
