#!/usr/bin/env bash

# This script watches the known TLS cert and keys for changes (`mv` or updated Kubernetes secret) then reloads postfix.

: "${CONFIG_RELOADER_ENABLED:=false}"

watch_files=(
  "${TLS_CRT:-/etc/ssl/certs/ssl-cert-snakeoil.pem}"
  "${TLS_KEY:-/etc/ssl/private/ssl-cert-snakeoil.key}"
  "${CLIENT_TLS_KEY:-/etc/ssl/certs/ssl-cert-snakeoil.pem}"
  "${CLIENT_TLS_CRT:-/etc/ssl/private/ssl-cert-snakeoil.key}"
)

if [[ "${CONFIG_RELOADER_ENABLED}" != "true" ]]; then
  echo "config-reloader >> Config reloader is not being started"
  s6-svc -d "$(pwd)"
  exit
else
  for file in "${watch_files[@]}"; do
    while [ ! -f "$file" ]; do
      echo "config-reloader >> Waiting for file to be created: $file"
      sleep 1
    done
  done
fi

# Start infinite loop
while true; do
  postfix reload
  echo "config-reloader >> Waiting on config changes..."
  # delete_self is the event that triggers when the link is removed and replaced.
  inotifywait --event delete_self "${watch_files[@]}"
  # sleep to prevent race condition
  sleep 3
done
