#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# Fix issue with dpkg-reconfigure and locales not installed "perl: warning: Setting locale failed."
unset LANG

cd /etc/s6/opendkim

# Defaults
: "${USE_DKIM:=no}"

# Exit if dkim disabled
if [ "${USE_DKIM}" != "yes" ]; then
	echo "dkim >> USE_DKIM = ${USE_DKIM}. Not starting opendkim."
	s6-svc -d "$(pwd)"
	exit
fi

# Render config template
/etc/opendkim.conf.sh

# exit cleanly
trap "{ /usr/sbin/service opendkim stop; }" EXIT

# start opendkim
/usr/sbin/service opendkim start

sleep 10 # wait for startup

# watch for opendkim exit
OPENDKIM_PID="$(pidof opendkim)"
while kill -0 "${OPENDKIM_PID}" 2>/dev/null; do
  sleep 1
done
